name: continues Integration

on:
        push:
                branches: [main]
        pull_request:
                branches: [main]
jobs:
        build-and-test:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - uses: Setup Node
                        - uses: actions/setup-node@v3
                          with:
                                  node-version: 18
                        - name: Install dependencies
                          run: npm install
                        - name: Run Tests
                          run: npm test
